matrix: Matrix< T, DefaultValue, N > Class Template Reference
Matrix< T, DefaultValue, N > Class Template Reference
Class N-dimensional matrix.
#include <Matrix.hpp>
Classes
class Proxy
Class Proxy - proxy element returned by the operator [].
Public Member Functions
Matrix ()=default
~Matrix ()=default
Proxy & operator[] (std::size_t index_part)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
std::size_t size ()
Private Types
using index_type = std::array< std::size_t, N >
using iterator = Iterator< T, N >
using const_iterator = const Iterator< T, N >
Private Member Functions
T & get_value (index_type index)
void set_value (index_type index, const T &value)
Private Attributes
std::map< index_type, T > _data
Proxy _proxy {*this}
T _default_value {DefaultValue}
Detailed Description
template<typename T, T DefaultValue, uint32_t N = 2>
class Matrix< T, DefaultValue, N >
Class N-dimensional matrix.
Template Parameters
T Matrix element type.
Parameters
DefaultValue Еhe default value of the element.
N Number of dimensions (N = 2 by default).
Definition at line 17 of file Matrix.hpp.
Member Typedef Documentation
const_iterator
template<typename T , T DefaultValue, uint32_t N = 2> using Matrix< T, DefaultValue, N >::const_iterator = const Iterator<T, N> private
Definition at line 21 of file Matrix.hpp.
index_type
template<typename T , T DefaultValue, uint32_t N = 2> using Matrix< T, DefaultValue, N >::index_type = std::array<std::size_t, N> private
Definition at line 19 of file Matrix.hpp.
iterator
template<typename T , T DefaultValue, uint32_t N = 2> using Matrix< T, DefaultValue, N >::iterator = Iterator<T, N> private
Definition at line 20 of file Matrix.hpp.
Constructor & Destructor Documentation
Matrix()
template<typename T , T DefaultValue, uint32_t N = 2> Matrix< T, DefaultValue, N >::Matrix () default
~Matrix()
template<typename T , T DefaultValue, uint32_t N = 2> Matrix< T, DefaultValue, N >::~Matrix () default
Member Function Documentation
begin() [1/2]
template<typename T , T DefaultValue, uint32_t N = 2> iterator Matrix< T, DefaultValue, N >::begin () inline
Definition at line 62 of file Matrix.hpp.
                     {
        return iterator(_data.begin());
    }
begin() [2/2]
template<typename T , T DefaultValue, uint32_t N = 2> const_iterator Matrix< T, DefaultValue, N >::begin () const inline
Definition at line 68 of file Matrix.hpp.
{
        return const_iterator(_data.begin());
    }
end() [1/2]
template<typename T , T DefaultValue, uint32_t N = 2> iterator Matrix< T, DefaultValue, N >::end () inline
Definition at line 65 of file Matrix.hpp.
                   {
        return iterator(_data.end());
    }
end() [2/2]
template<typename T , T DefaultValue, uint32_t N = 2> const_iterator Matrix< T, DefaultValue, N >::end () const inline
Definition at line 71 of file Matrix.hpp.
{
        return const_iterator(_data.end());
    }
get_value()
template<typename T , T DefaultValue, uint32_t N> T & Matrix< T, DefaultValue, N >::get_value (index_type index) private
Definition at line 88 of file Matrix.hpp.
{
    if (auto it = _data.find(index); it != _data.end()) {
        return it->second;
    } else {
        return _default_value;
    }
}
Referenced by Matrix< T, DefaultValue, N >::Proxy::operator T().
operator[]()
template<typename T , T DefaultValue, uint32_t N = 2> Proxy & Matrix< T, DefaultValue, N >::operator[] (std::size_t index_part) inline
Definition at line 58 of file Matrix.hpp.
{
        _proxy.first_index_part(index_part);
        return _proxy;
    }
set_value()
template<typename T , T DefaultValue, uint32_t N> void Matrix< T, DefaultValue, N >::set_value (index_type index, const T & value) private
Definition at line 97 of file Matrix.hpp.
{
    if (value == DefaultValue) {
        _data.erase(index);
    } else {
        _data.insert_or_assign(index, value);
    }
}
Referenced by Matrix< T, DefaultValue, N >::Proxy::operator=().
size()
template<typename T , T DefaultValue, uint32_t N = 2> std::size_t Matrix< T, DefaultValue, N >::size () inline
Definition at line 74 of file Matrix.hpp.
                     {
        return _data.size();
    }
Referenced by main().
Member Data Documentation
_data
template<typename T , T DefaultValue, uint32_t N = 2> std::map<index_type, T> Matrix< T, DefaultValue, N >::_data private
Definition at line 82 of file Matrix.hpp.
Referenced by Matrix< T, DefaultValue, N >::begin(), Matrix< T, DefaultValue, N >::end(), and Matrix< T, DefaultValue, N >::size().
_default_value
template<typename T , T DefaultValue, uint32_t N = 2> T Matrix< T, DefaultValue, N >::_default_value {DefaultValue} private
Definition at line 84 of file Matrix.hpp.
_proxy
template<typename T , T DefaultValue, uint32_t N = 2> Proxy Matrix< T, DefaultValue, N >::_proxy {*this} private
Definition at line 83 of file Matrix.hpp.
Referenced by Matrix< T, DefaultValue, N >::operator[]().
The documentation for this class was generated from the following file:
Matrix.hpp